node {
    stage ("Create build output") {

        //Make output directory

    sh "mkdir -p output"

        // Write a useful file that neds to be archived

    writeFile file: "output/usefulfile.txt", text: "This file is useful"
    }
    stage ("Archive build output") {

  
    archiveArtifacts artifacts: 'output/*.txt'
    }


}